version: '3.7'
services:
  stockvipalerts:
    container_name: NSSAlerts
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./config
        target: /config
    restart: always
    env_file:
      - .env